---
title: "Practica 2"
author: "Estadística avanzada"
date: "Diciembre 2021"
output:
  html_document:
    number_sections: no
    toc: yes
    toc_depth: 2
  pdf_document: 
    number_section: no
    toc: yes
    latex_engine: xelatex
lang: es
---

******
# 1- Descripción del dataset
******

******
# 2- Integración y selección de los datos de interés
******

******
# 3- Limpieza de datos
******

## 3.1 - Valores perdidos

## 3.2 - Identificación y tratamiento de valores extremos


******
# 4- Análisis de datos
******

## 4.1 - Selección del grupo de datos que se quiere analizar

## 4.2 - Comprobación de la normailidad y homogeneidad de la varianza

## 4.3 - Pruebas estadísticas

******
# 5- Representación de los resultados
******

******
# 6- Resolución del problema
******


### Apartado a

### Apartado b


## 1.2 - Modelo de regresión lineal

### Apartado a


### Apartado b


## 1.3 - Modelo de regresión lineal multiple

### Apartado a

### Apartado b


### Apartado c


## 1.4 - Diagnosis del modelo


## 1.5 - Predicción del modelo


******
# 2- Regresión logística
******
## 2.1 - Estudio de relaciones entre variables. Análisis crudo de posibles factores de riesgo

### Apartado a



### Apartado b




## 2.2 - Modelo de regresión logística

### Apartado a


### Apartado b


### Apartado c

### Apartado d


## 2.3 - Predicción


## 2.4 - Bondad del Ajuste



## 2.5 - Curva ROC


******
# 3- Conclusiones
******

